import os
import inspect
import SCons

# try to import an environment first
Import('env')

# find all .cus & .cpps in the current and backend/ directories
extensions = ['*.cu', '*.cpp']

for ext in extensions:
  regexp = os.path.join('.', ext)
  sources = env.Glob(regexp)

  for source in sources:
    env.Program(source)
    print(source)

"""
env.MSVSProject(target="blas" + env['MSVSPROJECTSUFFIX'],
                srcs=['blas.cu'],
                variant='Release')
env.MSVSProject(target="multiply" + env['MSVSPROJECTSUFFIX'],
                srcs=['multiply.cu'],
                variant='Release')
"""            